"""Auto-generated type stubs for IncludeCPP module wrappers.

This file enables VSCode IntelliSense autocomplete for C++ modules.
DO NOT EDIT - Auto-generated by IncludeCPP build system.
"""

from typing import Any, List, Dict, Optional, Union, Protocol, overload

class Cssc_accelModuleWrapper(Protocol):
    """Type hints for cssc_accel module wrapper (VSCode autocomplete support)."""

    def getInfo(self) -> Dict[str, Any]:
        """Get cssc_accel module information."""
        ...

    class CsscScope:
        """C++ class: CsscScope"""

        def __init__(self) -> None:
            """Initialize CsscScope instance"""
            ...

        def clear(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: clear"""
            ...

        def count(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: count"""
            ...

        def get_bool(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: get_bool"""
            ...

        def get_float(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: get_float"""
            ...

        def get_int(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: get_int"""
            ...

        def get_str(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: get_str"""
            ...

        def get_type(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: get_type"""
            ...

        def has(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: has"""
            ...

        def increment_int(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: increment_int"""
            ...

        def remove(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: remove"""
            ...

        def set_bool(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: set_bool"""
            ...

        def set_float(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: set_float"""
            ...

        def set_int(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: set_int"""
            ...

        def set_string(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: set_string"""
            ...

        def update_float(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: update_float"""
            ...

        def update_int(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: update_int"""
            ...


    def batch_add(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: batch_add"""
        ...

    def batch_compare_lt(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: batch_compare_lt"""
        ...

    def batch_mul(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: batch_mul"""
        ...

    def binary_op_int(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: binary_op_int"""
        ...

    def binary_op_num(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: binary_op_num"""
        ...

    def compare_num(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: compare_num"""
        ...

    def compare_str(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: compare_str"""
        ...

    def decode_bool(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: decode_bool"""
        ...

    def decode_float(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: decode_float"""
        ...

    def decode_int(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: decode_int"""
        ...

    def decode_str(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: decode_str"""
        ...

    def decode_tag(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: decode_tag"""
        ...

    def encode_bool(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: encode_bool"""
        ...

    def encode_float(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: encode_float"""
        ...

    def encode_int(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: encode_int"""
        ...

    def encode_null(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: encode_null"""
        ...

    def encode_str(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: encode_str"""
        ...

    def fast_concat(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: fast_concat"""
        ...

    def fast_repeat(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: fast_repeat"""
        ...

    def for_iteration_count(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: for_iteration_count"""
        ...

    def for_range(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: for_range"""
        ...

    def int_to_str(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: int_to_str"""
        ...

    def logical_and(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: logical_and"""
        ...

    def logical_not(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: logical_not"""
        ...

    def logical_or(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: logical_or"""
        ...

    def num_to_str(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: num_to_str"""
        ...

    def to_bool_int(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: to_bool_int"""
        ...

    def to_bool_num(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: to_bool_num"""
        ...

    def to_bool_str(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: to_bool_str"""
        ...

    def to_int(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: to_int"""
        ...

    def to_number(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: to_number"""
        ...



class Cssc_coreModuleWrapper(Protocol):
    """Type hints for cssc_core module wrapper (VSCode autocomplete support)."""

    def getInfo(self) -> Dict[str, Any]:
        """Get cssc_core module information."""
        ...

    def run_cssc(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: run_cssc"""
        ...

    def cssc_version(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: cssc_version"""
        ...



class Cssc_math_accelModuleWrapper(Protocol):
    """Type hints for cssc_math_accel module wrapper (VSCode autocomplete support)."""

    def getInfo(self) -> Dict[str, Any]:
        """Get cssc_math_accel module information."""
        ...

    def hash2(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: hash2"""
        ...

    def hash3(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: hash3"""
        ...

    def hash4(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: hash4"""
        ...

    def hashUnit(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: hashUnit"""
        ...

    def hashUnit3(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: hashUnit3"""
        ...

    def fade(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: fade"""
        ...

    def lerpf(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: lerpf"""
        ...

    def clampf(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: clampf"""
        ...

    def smoothstep(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: smoothstep"""
        ...

    def smootherstep(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: smootherstep"""
        ...

    def floorf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: floorf_"""
        ...

    def ceilf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: ceilf_"""
        ...

    def roundf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: roundf_"""
        ...

    def absf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: absf_"""
        ...

    def sqrtf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: sqrtf_"""
        ...

    def sinf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: sinf_"""
        ...

    def cosf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: cosf_"""
        ...

    def tanf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: tanf_"""
        ...

    def atan2f_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: atan2f_"""
        ...

    def powf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: powf_"""
        ...

    def expf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: expf_"""
        ...

    def logf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: logf_"""
        ...

    def minf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: minf_"""
        ...

    def maxf_(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: maxf_"""
        ...

    def floori(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: floori"""
        ...

    def valueNoise2(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: valueNoise2"""
        ...

    def fbm2(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: fbm2"""
        ...

    def perlin2(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: perlin2"""
        ...

    def perlinFbm2(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: perlinFbm2"""
        ...

    def fbm2_grid(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: fbm2_grid"""
        ...

    def perlinFbm2_grid(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: perlinFbm2_grid"""
        ...

    def worldgen_tile_at(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: worldgen_tile_at"""
        ...

    def worldgen_tile_grid(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: worldgen_tile_grid"""
        ...

    def worldgen_is_solid_at(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: worldgen_is_solid_at"""
        ...

    def worldgen_collide_aabb(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: worldgen_collide_aabb"""
        ...

    def lerp_array(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: lerp_array"""
        ...

    def clamp_array(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: clamp_array"""
        ...

    def threshold_array(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: threshold_array"""
        ...

    def distance_array(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: distance_array"""
        ...



class Cssc_video_accelModuleWrapper(Protocol):
    """Type hints for cssc_video_accel module wrapper (VSCode autocomplete support)."""

    def getInfo(self) -> Dict[str, Any]:
        """Get cssc_video_accel module information."""
        ...

    def blit_bitmap(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: blit_bitmap"""
        ...

    def blit_bitmap_scaled(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: blit_bitmap_scaled"""
        ...

    def blit_bitmap_tinted(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: blit_bitmap_tinted"""
        ...

    def blit_bitmap_alpha(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: blit_bitmap_alpha"""
        ...

    def blit_tile_grid(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: blit_tile_grid"""
        ...

    def clear_framebuffer(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: clear_framebuffer"""
        ...

    def fill_rect_native(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: fill_rect_native"""
        ...

    def fill_rect_alpha(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: fill_rect_alpha"""
        ...



class Cssl_coreModuleWrapper(Protocol):
    """Type hints for cssl_core module wrapper (VSCode autocomplete support)."""

    def getInfo(self) -> Dict[str, Any]:
        """Get cssl_core module information."""
        ...

    class Lexer:
        """C++ class: Lexer"""

        def __init__(self, arg0: str) -> None:
            """Initialize Lexer instance"""
            ...

        def tokenize(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: tokenize"""
            ...


    class Token:
        """C++ class: Token"""

        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: int, arg2: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: str, arg2: int, arg3: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: float, arg2: int, arg3: int) -> None: ...
        @overload
        def __init__(self, arg0: int, arg1: bool, arg2: int, arg3: int) -> None: ...

        def __init__(self, *args: Any, **kwargs: Any) -> None:
            """Initialize Token instance"""
            ...

        pass

    class Interpreter:
        """C++ class: Interpreter"""

        def __init__(self) -> None:
            """Initialize Interpreter instance"""
            ...

        def run(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: run"""
            ...

        def run_string(self, *args: Any, **kwargs: Any) -> Any:
            """C++ method: run_string"""
            ...


    def run_cssl(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: run_cssl"""
        ...

    def version(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: version"""
        ...

    def is_keyword(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: is_keyword"""
        ...

    def str_concat(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_concat"""
        ...

    def str_contains(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_contains"""
        ...

    def str_join(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_join"""
        ...

    def str_lower(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_lower"""
        ...

    def str_replace(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_replace"""
        ...

    def str_split(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_split"""
        ...

    def str_trim(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_trim"""
        ...

    def str_upper(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_upper"""
        ...

    def str_reverse(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_reverse"""
        ...

    def str_len(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_len"""
        ...

    def str_repeat(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_repeat"""
        ...

    def str_startswith(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_startswith"""
        ...

    def str_endswith(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_endswith"""
        ...

    def str_indexof(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_indexof"""
        ...

    def str_substr(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_substr"""
        ...

    def str_cmp(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: str_cmp"""
        ...

    def math_clamp(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_clamp"""
        ...

    def math_ipow(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_ipow"""
        ...

    def math_pow(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_pow"""
        ...

    def math_mod(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_mod"""
        ...

    def math_abs(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_abs"""
        ...

    def math_min(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_min"""
        ...

    def math_max(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_max"""
        ...

    def math_floor(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_floor"""
        ...

    def math_ceil(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: math_ceil"""
        ...

    def array_sum(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: array_sum"""
        ...

    def array_isum(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: array_isum"""
        ...

    def array_avg(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: array_avg"""
        ...

    def array_min(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: array_min"""
        ...

    def array_max(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: array_max"""
        ...

    def range(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: range"""
        ...

    def loop_check_lt(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: loop_check_lt"""
        ...

    def loop_check_le(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: loop_check_le"""
        ...

    def loop_check_gt(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: loop_check_gt"""
        ...

    def loop_check_ge(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: loop_check_ge"""
        ...

    def num_cmp(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: num_cmp"""
        ...

    def eq_int(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: eq_int"""
        ...

    def eq_float(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: eq_float"""
        ...

    def eq_str(self, *args: Any, **kwargs: Any) -> Any:
        """C++ function: eq_str"""
        ...



# CppApi with typed include() overloads for each module
class CppApi:
    """C++ API Manager with typed module loading.

    The include() method returns a module wrapper with full type hints
    for VSCode/PyCharm autocomplete support.
    """

    def __init__(self, project_root: Optional[str] = None, auto_update: bool = True) -> None:
        """Initialize CppApi.

        Args:
            project_root: Path to project root (default: auto-detect)
            auto_update: Whether to auto-rebuild on source changes
        """
        ...

    @overload
    def include(self, module_name: str = "cssc_accel", auto_update: Optional[bool] = None) -> Cssc_accelModuleWrapper: ...

    @overload
    def include(self, module_name: str = "cssc_core", auto_update: Optional[bool] = None) -> Cssc_coreModuleWrapper: ...

    @overload
    def include(self, module_name: str = "cssc_math_accel", auto_update: Optional[bool] = None) -> Cssc_math_accelModuleWrapper: ...

    @overload
    def include(self, module_name: str = "cssc_video_accel", auto_update: Optional[bool] = None) -> Cssc_video_accelModuleWrapper: ...

    @overload
    def include(self, module_name: str = "cssl_core", auto_update: Optional[bool] = None) -> Cssl_coreModuleWrapper: ...

    @overload
    def include(self, module_name: str, auto_update: Optional[bool] = None) -> Any: ...

    def include(self, module_name: str, auto_update: Optional[bool] = None) -> Any:
        """Load a C++ module.

        Args:
            module_name: Name of the module to load
            auto_update: Override auto-update setting for this module

        Returns:
            ModuleWrapper with access to C++ classes, functions, and structs
        """
        ...

    def rebuild(self, verbose: bool = False) -> bool:
        """Rebuild all C++ modules."""
        ...

    def list_modules(self) -> List[str]:
        """List available modules."""
        ...
