#!/usr/bin/env python3
"""
Build a real web font from CSSC's own 8x8 video font.

Source of truth is CCOS/build/out/font_init_hex.txt, the same glyph
data the video module pokes into memory to draw text on an OLED. Each glyph is
one uint64: 8 rows of 8 bits, row 0 at the top, bit 0 at the left.

The website renders its text in this font, so the page and the panel use the
same letterforms. Nothing here is redrawn or approximated.

Output: CSSCPixel.woff and CSSCPixel.ttf next to this script.

Metrics. One source pixel is 64 font units, so the em box is 8x8 pixels at
512 units. Capitals occupy rows 0..6 and descenders reach row 7, which puts the
baseline under row 6: ascent 448 (7px), descent 64 (1px). Advance is a full
8px cell, because the font is monospaced and the IDE draws it on a fixed grid.
"""

import base64
import re
import sys
from pathlib import Path

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

HERE = Path(__file__).resolve().parent
# Vendored copy of CSSC/CCOS/build/out/font_init_hex.txt, so this repo can
# rebuild the font on its own. Re-copy it if the glyphs ever change.
SOURCE = HERE / "font_init_hex.txt"

PIXEL = 64          # font units per source pixel
EM = 8 * PIXEL      # 512
ASCENT = 7 * PIXEL  # 448, rows 0..6 sit above the baseline
DESCENT = 1 * PIXEL # 64, row 7 hangs below it
FIRST = 32
LAST = 127


def load_glyph_bits(path):
    """code point -> [[bit, ...8], ...8], row 0 top, column 0 left."""
    text = path.read_text(encoding="utf-8", errors="replace")
    entries = re.findall(r"ciFont \+ (\d+),\s*(0x[0-9A-Fa-f]+)", text, re.S)
    if not entries:
        sys.exit(f"no glyph data found in {path}")

    glyphs = {}
    for offset, value in entries:
        code = FIRST + int(offset) // 8
        packed = int(value, 16)
        glyphs[code] = [
            [(packed >> (row * 8 + col)) & 1 for col in range(8)]
            for row in range(8)
        ]
    return glyphs


def to_rects(bits):
    """Cover the lit pixels with as few rectangles as possible.

    One contour per pixel would work but triples the file size, so this grows
    each run to the right and then down for as long as the block stays solid.
    A typical glyph drops from ~20 contours to ~8.
    """
    used = [[False] * 8 for _ in range(8)]
    rects = []

    for row in range(8):
        col = 0
        while col < 8:
            if not bits[row][col] or used[row][col]:
                col += 1
                continue

            width = 0
            while col + width < 8 and bits[row][col + width] and not used[row][col + width]:
                width += 1

            height = 1
            while row + height < 8:
                solid = all(
                    bits[row + height][col + i] and not used[row + height][col + i]
                    for i in range(width)
                )
                if not solid:
                    break
                height += 1

            for r in range(row, row + height):
                for c in range(col, col + width):
                    used[r][c] = True

            rects.append((col, row, width, height))
            col += width

    return rects


def draw(pen, rects):
    """Emit each rectangle clockwise in y-up font coordinates."""
    for col, row, width, height in rects:
        x0 = col * PIXEL
        x1 = (col + width) * PIXEL
        y_top = (7 - row) * PIXEL
        y_bottom = (7 - row - height) * PIXEL

        pen.moveTo((x0, y_bottom))
        pen.lineTo((x0, y_top))
        pen.lineTo((x1, y_top))
        pen.lineTo((x1, y_bottom))
        pen.closePath()


def preview(bits):
    return "\n".join(
        "".join("#" if bit else "." for bit in row) for row in bits
    )


def write_font_css(woff2_path, woff_path):
    """Emit web/font.css with the font inlined as data URIs.

    Inlining costs a few kilobytes and buys two things: the page renders in one
    round trip, and it still works when you open index.html straight from disk,
    where browsers refuse to load font files over file://.
    """
    woff2 = base64.b64encode(woff2_path.read_bytes()).decode("ascii")
    woff = base64.b64encode(woff_path.read_bytes()).decode("ascii")

    css = (
        "/* Generated by webtools/make_font.py. Do not edit by hand.\n"
        "   CSSC Pixel is the 8x8 font CSSC's video module draws with,\n"
        "   taken straight from CSSC/CCOS/build/out/font_init_hex.txt. */\n"
        "@font-face {\n"
        '  font-family: "CSSC Pixel";\n'
        "  font-style: normal;\n"
        "  font-weight: 400;\n"
        "  font-display: block;\n"
        f'  src: url(data:font/woff2;base64,{woff2}) format("woff2"),\n'
        f'       url(data:font/woff;base64,{woff}) format("woff");\n'
        "}\n"
    )

    out = HERE.parent / "web" / "font.css"
    out.write_text(css, encoding="utf-8")
    return out


def main():
    glyph_bits = load_glyph_bits(SOURCE)

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyph_bits]
    if missing:
        sys.exit(f"missing glyphs for code points: {missing}")

    glyph_order = [".notdef"]
    glyphs = {".notdef": TTGlyphPen(None).glyph()}
    char_map = {}
    metrics = {".notdef": (EM, 0)}
    rect_count = 0

    for code in range(FIRST, LAST + 1):
        name = f"uni{code:04X}"
        glyph_order.append(name)
        char_map[code] = name

        rects = to_rects(glyph_bits[code])
        rect_count += len(rects)

        pen = TTGlyphPen(None)
        draw(pen, rects)
        glyphs[name] = pen.glyph()

        left = min((c for c, _, _, _ in rects), default=0) * PIXEL
        metrics[name] = (EM, left)

    fb = FontBuilder(unitsPerEm=EM, isTTF=True)
    fb.setupGlyphOrder(glyph_order)
    fb.setupCharacterMap(char_map)
    fb.setupGlyf(glyphs)
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=ASCENT, descent=-DESCENT, lineGap=0)
    fb.setupNameTable({
        "familyName": "CSSC Pixel",
        "styleName": "Regular",
        "uniqueFontIdentifier": "CSSC Pixel Regular; cssclang.com",
        "fullName": "CSSC Pixel Regular",
        "psName": "CSSCPixel-Regular",
        "version": "Version 1.000",
        "manufacturer": "lilias hatterscheidt",
        "designer": "lilias hatterscheidt",
        "description": "The 8x8 font CSSC's video module draws with, as a web font.",
    })
    fb.setupOS2(
        sTypoAscender=ASCENT,
        sTypoDescender=-DESCENT,
        sTypoLineGap=0,
        usWinAscent=ASCENT,
        usWinDescent=DESCENT,
        sCapHeight=ASCENT,
        sxHeight=5 * PIXEL,
        xAvgCharWidth=EM,
        achVendID="CSSC",
        panose=dict(
            bFamilyType=2, bSerifStyle=11, bWeight=5, bProportion=9,
            bContrast=0, bStrokeVariation=0, bArmStyle=0, bLetterForm=0,
            bMidline=0, bXHeight=0,
        ),
    )
    fb.setupPost(isFixedPitch=1, underlinePosition=-2 * PIXEL, underlineThickness=PIXEL)

    ttf_path = HERE / "CSSCPixel.ttf"
    woff_path = HERE / "CSSCPixel.woff"
    woff2_path = HERE / "CSSCPixel.woff2"

    fb.save(str(ttf_path))
    fb.font.flavor = "woff"
    fb.save(str(woff_path))
    fb.font.flavor = "woff2"
    fb.save(str(woff2_path))

    print(f"source     {SOURCE}")
    print(f"glyphs     {len(char_map)} (U+{FIRST:04X}..U+{LAST:04X})")
    print(f"contours   {rect_count} rectangles total, "
          f"{rect_count / len(char_map):.1f} per glyph")
    print(f"metrics    em {EM}, ascent {ASCENT}, descent {DESCENT}, advance {EM}")
    css_path = write_font_css(woff2_path, woff_path)

    print(f"ttf        {ttf_path.stat().st_size:,} bytes")
    print(f"woff       {woff_path.stat().st_size:,} bytes")
    print(f"woff2      {woff2_path.stat().st_size:,} bytes")
    print(f"css        {css_path} ({css_path.stat().st_size:,} bytes)")
    print()
    print("sanity check, the C from the logo:")
    print(preview(glyph_bits[ord("C")]))


if __name__ == "__main__":
    main()
